services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/chat-app
    depends_on:
      - db
      - react

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  react:
    build:
      context: .
      dockerfile: ./assets/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/chat-app
      - /chat-app/node_modules
    command: npm run dev -- --host

  redis:
      image: redis:latest
      command: redis-server --timeout 300 --tcp-keepalive 60 --appendonly yes
      container_name: my-redis
      ports:
          - '6379:6379'
      volumes:
          - redis-data:/data
      restart: unless-stopped

volumes:
  postgres_data:
  redis-data:
