# Generated by Django 6.0.5 on 2026-06-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_friend_request_friendrequests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                ("filesize", models.BigIntegerField()),
                ("data", models.FileField(upload_to="attachments")),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="chats",
            old_name="type",
            new_name="chat_type",
        ),
        migrations.AddField(
            model_name="chats",
            name="image",
            field=models.ImageField(default="default.png", upload_to="chats"),
        ),
        migrations.AddConstraint(
            model_name="chats",
            constraint=models.CheckConstraint(
                condition=models.Q(("chat_type__in", ["DM", "Groupchat"])),
                name="valid_chat_type_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequests",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["Pending", "Accepted", "Rejected"])),
                name="valid_status_constraint",
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.chats"
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="attachments",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.messages"
            ),
        ),
    ]
